services:
  max2tg:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      LOG_DIR: /app/logs
      STATE_DIR: /app/state
    volumes:
      - ./logs:/app/logs
      - ./state:/app/state
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
